### ISSUE TITLE
: No such file or directory

### ISSUE THREAD

**Issue by DecusAnima** [samuelkadolph/truenas-telegraf#4]
Running the install file in TrueNAS-13.0-U6.1 yields ": No such file or directory"

![image](https://github.com/samuelkadolph/truenas-telegraf/assets/132281597/36b016e4-cb8a-4361-9cc7-7f066ee1ef1e)

**Comment by samuelkadolph** [comment]
That's an odd one. I upgraded to U6.1 last night and just ran the install script successfully. Can you run the following commands in that directory and copy+paste here?

```
which python
ls -l
git show --oneline -s
md5sum install
```

**Comment by DecusAnima** [comment]
![image](https://github.com/samuelkadolph/truenas-telegraf/assets/132281597/5fe9a1a7-631c-4251-96ff-5cd188217f42)

also went ahead and chmod 777 the install command to make sure it wasn't an execution permission issue

**Comment by samuelkadolph** [comment]
I get a different hash for install with 6027e97: bdf5e9c51d5871ec8cf15371d231adf6. Did you make any changes to the fire by chance? Also I see there's extended attributes on the files. Maybe try installing from a dataset with just normal unix permissions or from /root. If you run `diff install <(curl -L https://github.com/samuelkadolph/truenas-telegraf/raw/main/install)` are there any differences?

**Comment by DecusAnima** [comment]
can't say what happened, but deleting the clone and re-cloning it fixed the issue, thanks.
